[tools]
rust = "latest"

[tasks.build]
description = "Build the CLI"
run = "cd omawarden && cargo build"

[tasks.dev-cli]
description = "Run the CLI in development mode"
run = "cd omawarden && cargo run --"

[tasks.build-release]
description = "Build the CLI in release mode"
run = "cd omawarden && cargo build --release && mkdir -p ../bin && cp -f target/release/omawarden ../bin/omawarden"

[tasks.dev-update-omarchy-plugin]
description = "Update the Omarchy plugin in development mode"
run = """
BRANCH=$(git branch --show-current)
cd ~/.config/omarchy/plugins/icyleaf.bitwarden
git fetch origin
git checkout "$BRANCH"
git merge "origin/$BRANCH"
"""

[tasks.dev-restart-omarchy]
description = "Restart the Omarchy plugin in development mode"
run = "omarchy-restart-shell"

[tasks.dev-deploy]
description = "Deploy the CLI in development mode"
depends = ["build-release", "dev-update-omarchy-plugin"]
depends_post = ["dev-restart-omarchy"]
run = "mkdir -p ~/.config/omarchy/plugins/icyleaf.bitwarden/bin && cp -f bin/omawarden ~/.config/omarchy/plugins/icyleaf.bitwarden/bin/omawarden"

