name: CI

on:
  push:
    branches:
      - main
      - develop
      - feat/*
      - fix/*
      - sec/*
      - chore/*
      - ci/*
      - refactor/*
    paths:
      - "omawarden/**"
      - "scripts/**"
      - "tests/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "omawarden/**"
      - "scripts/**"
      - "tests/**"
      - ".github/workflows/ci.yml"

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: omawarden
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsecret-tools

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
        with:
          components: rustfmt, clippy

      - name: Rust cache
        uses: Swatinem/rust-cache@400e7407cfd7a091e5fbb6afec01ec146c432b7c # v2.7.7
        with:
          workspaces: omawarden -> target

      - name: Check code formatting
        run: cargo fmt --check

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Run test suite
        run: cargo test --all-targets
